spring.application.name=quanlyhocvien

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quanlyhocvien
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

file.upload-dir=./src/main/resources/static/images


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=azazaz2812004@gmail.com
spring.mail.password=0352712217H
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#For picture
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Application URL for verification links
app.base-url=http://localhost:8080

spring.thymeleaf.cache=false

app.jwt.secret=YNXk3bPfqTxPt8vmHmPCt6G8yVgAm98mHqvK3yMGFk4a4ypzU2jKE2Md5NcECurJpwtD9fK5AxxcBvYSLVF6Fx8Ur7a2QV8Br5Pwe9HJXXzbx6DvGTLyNqkbFJ3uKDjr
app.jwt.expiration=86400000

